// Centralized 52 Product Dataset for DualForge E-Commerce Platform

export const get50PlusCatalogProducts = () => {
  const cElec = { id: 1, name: 'Electronics' };
  const cFoot = { id: 2, name: 'Footwear' };
  const cApp = { id: 3, name: 'Fashion' };

  return [
    { id: 1, name: "Forgebook Pro 16", price: 124999, imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500", category: cElec, brand: "Forge", rating: 4.8, reviewCount: 124, stockQuantity: 15, lowStockThreshold: 3, discountPercent: 15, description: "Architectural-grade workhorse laptop featuring liquid metal cooling & 32GB RAM.", variants: "Color: Space Gray, Silver | RAM: 16GB, 32GB", warranty: "1 Year Domestic Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "laptop,workstation,forgebook" },
    { id: 2, name: "Forgebuds ANC", price: 4999, imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500", category: cElec, brand: "ForgeAudio", rating: 4.6, reviewCount: 188, stockQuantity: 50, lowStockThreshold: 5, discountPercent: 10, description: "Studio acoustics, active noise cancellation, and 40h hybrid reserve battery cell.", variants: "Color: Stealth Black, Arctic White", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "buds,anc,audio,headphone" },
    { id: 3, name: "Stealth Runners", price: 3499, imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500", category: cFoot, brand: "Stealth", rating: 4.7, reviewCount: 254, stockQuantity: 30, lowStockThreshold: 5, discountPercent: 20, description: "Hydrophobic mesh structure with ultra-rebound compound outsoles for marathon training.", variants: "Color: Red, Neon Blue, Charcoal Gray | Size: 7, 8, 9, 10, 11", warranty: "3 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 149, tags: "run,stealth,shoes,sneaker" },
    { id: 4, name: "Tech Hoodie Black", price: 2499, imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500", category: cApp, brand: "ForgeWear", rating: 4.8, reviewCount: 85, stockQuantity: 40, lowStockThreshold: 5, discountPercent: 10, description: "Wind-resistant thermo-regulating fleece hoodie with concealed internal travel slots.", variants: "Size: S, M, L, XL | Color: Charcoal Black, Tech Gray", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,hoodie,black,sweatshirt" },
    
    // Expanded 48 items
    { id: 101, name: "Cyberpunk Oversized Hoodie", price: 3299, imageUrl: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=500", category: cApp, brand: "CyberForge", rating: 4.9, reviewCount: 120, stockQuantity: 25, lowStockThreshold: 4, discountPercent: 15, description: "Heavyweight 450GSM organic cotton oversized fleece hoodie.", variants: "Size: M, L, XL, XXL | Color: Neon Green, Stealth Gray", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,hoodie,cyberpunk,oversized" },
    { id: 102, name: "Minimalist Zip Fleece Hoodie", price: 1999, imageUrl: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=500", category: cApp, brand: "ForgeWear", rating: 4.5, reviewCount: 64, stockQuantity: 60, lowStockThreshold: 5, discountPercent: 5, description: "Full-zip thermal insulator hoodie for gym and outdoor travel.", variants: "Size: S, M, L | Color: Navy, Olive Green", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,hoodie,zip,fleece" },
    { id: 103, name: "Urban Bomber Jacket", price: 4499, imageUrl: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=500", category: cApp, brand: "ForgeWear", rating: 4.7, reviewCount: 98, stockQuantity: 30, lowStockThreshold: 4, discountPercent: 20, description: "Weatherproof bomber jacket with padded thermal lining.", variants: "Size: M, L, XL | Color: Army Green, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,jacket,bomber,urban" },
    { id: 104, name: "Denim Trucker Jacket", price: 3799, imageUrl: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500", category: cApp, brand: "DenimForge", rating: 4.6, reviewCount: 52, stockQuantity: 18, lowStockThreshold: 3, discountPercent: 10, description: "Vintage washed rugged denim jacket with sherpa collar.", variants: "Size: S, M, L, XL | Color: Washed Blue, Vintage Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 4, shippingCharges: 99, tags: "apparel,jacket,denim,trucker" },
    { id: 105, name: "Slim Fit Tapered Jeans", price: 2299, imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500", category: cApp, brand: "DenimForge", rating: 4.4, reviewCount: 76, stockQuantity: 50, lowStockThreshold: 5, discountPercent: 15, description: "Stretch denim jeans designed for everyday ergonomic comfort.", variants: "Size: 30, 32, 34, 36 | Color: Dark Blue, Black", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,jeans,denim,slim" },
    { id: 106, name: "Graphic Oversized Tee", price: 1199, imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500", category: cApp, brand: "ForgeWear", rating: 4.6, reviewCount: 140, stockQuantity: 80, lowStockThreshold: 10, discountPercent: 10, description: "Breathable combed cotton streetwear graphic t-shirt.", variants: "Size: S, M, L, XL | Color: White, Black, Purple", warranty: "No Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "apparel,tshirt,tee,graphic" },
    { id: 107, name: "Polo Performance Shirt", price: 1499, imageUrl: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=500", category: cApp, brand: "ForgeWear", rating: 4.5, reviewCount: 48, stockQuantity: 45, lowStockThreshold: 5, discountPercent: 5, description: "Moisture-wicking breathable polo shirt for casual & sports.", variants: "Size: M, L, XL | Color: Royal Blue, White, Charcoal", warranty: "No Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,polo,shirt,performance" },

    { id: 108, name: "ForgePro Wireless Gaming Headset", price: 6499, imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500", category: cElec, brand: "ForgeAudio", rating: 4.8, reviewCount: 142, stockQuantity: 35, lowStockThreshold: 4, discountPercent: 15, description: "Low-latency 2.4GHz wireless headset with detachable spatial mic.", variants: "Color: Cyber Red, Matte Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "headphone,gaming,wireless,headset" },
    { id: 109, name: "AcousticBass Studio Headphones", price: 7999, imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500", category: cElec, brand: "AcousticForge", rating: 4.9, reviewCount: 95, stockQuantity: 20, lowStockThreshold: 3, discountPercent: 20, description: "Professional monitor headphones with 50mm drivers for sound engineers.", variants: "Color: Gold Accent, Black", warranty: "2 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "headphone,studio,monitor,audio" },
    { id: 110, name: "PocketPods Mini TWS", price: 1999, imageUrl: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=500", category: cElec, brand: "ForgeAudio", rating: 4.4, reviewCount: 210, stockQuantity: 70, lowStockThreshold: 8, discountPercent: 25, description: "Ultra-compact true wireless earbuds with magnetic fast charging case.", variants: "Color: Arctic White, Cyan", warranty: "6 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "headphone,earphone,tws,buds" },
    { id: 111, name: "BoomBlast Portable Speaker", price: 3499, imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500", category: cElec, brand: "ForgeAudio", rating: 4.7, reviewCount: 115, stockQuantity: 40, lowStockThreshold: 5, discountPercent: 10, description: "IPX7 waterproof 30W Bluetooth speaker with deep bass radiator.", variants: "Color: Army Camo, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "speaker,audio,bluetooth,waterproof" },
    { id: 112, name: "SoundBar Surround 120W", price: 9999, imageUrl: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500", category: cElec, brand: "ForgeAudio", rating: 4.8, reviewCount: 73, stockQuantity: 15, lowStockThreshold: 2, discountPercent: 15, description: "Cinema-grade 2.1 channel soundbar with wireless subwoofer.", variants: "Color: Piano Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 4, shippingCharges: 199, tags: "soundbar,speaker,home theater" },

    { id: 113, name: "Apex Velocity Sneakers", price: 5999, imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500", category: cFoot, brand: "ApexForge", rating: 4.9, reviewCount: 165, stockQuantity: 20, lowStockThreshold: 3, discountPercent: 15, description: "Lightweight carbon-plated marathon racing shoes.", variants: "Size: 8, 9, 10, 11 | Color: Volt Yellow, White", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "shoe,sneaker,velocity,running" },
    { id: 114, name: "Classic Leather Oxfords", price: 4999, imageUrl: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500", category: cFoot, brand: "LeatherForge", rating: 4.6, reviewCount: 82, stockQuantity: 25, lowStockThreshold: 4, discountPercent: 10, description: "Handcrafted Italian genuine leather formal Oxford dress shoes.", variants: "Size: 7, 8, 9, 10 | Color: Tan Brown, Onyx Black", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "shoe,formal,oxford,leather" },
    { id: 115, name: "Urban High-Top Sneakers", price: 3999, imageUrl: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=500", category: cFoot, brand: "StreetForge", rating: 4.8, reviewCount: 190, stockQuantity: 35, lowStockThreshold: 5, discountPercent: 15, description: "Retro basketball style high-top sneakers with ankle support.", variants: "Size: 7, 8, 9, 10, 11 | Color: White/Red, Black/Gold", warranty: "3 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "shoe,sneaker,hightop,streetwear" },
    { id: 116, name: "TrailBlazer Hiking Boots", price: 6999, imageUrl: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=500", category: cFoot, brand: "TrailForge", rating: 4.9, reviewCount: 110, stockQuantity: 15, lowStockThreshold: 2, discountPercent: 10, description: "Waterproof Vibram sole rugged outdoor trekking boots.", variants: "Size: 8, 9, 10, 11 | Color: Earth Brown, Charcoal", warranty: "1 Year Warranty", estimatedDeliveryDays: 4, shippingCharges: 0, tags: "shoe,boot,hiking,outdoor" },
    { id: 117, name: "Breathable Slip-On Loafers", price: 2499, imageUrl: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=500", category: cFoot, brand: "CasualForge", rating: 4.5, reviewCount: 78, stockQuantity: 50, lowStockThreshold: 5, discountPercent: 20, description: "Ultra-light memory foam casual slip-on driving loafers.", variants: "Size: 7, 8, 9, 10 | Color: Navy, Gray, Beige", warranty: "3 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "shoe,loafer,slipon,casual" },

    { id: 118, name: "Forgebook Ultra 14", price: 84999, imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500", category: cElec, brand: "Forge", rating: 4.9, reviewCount: 156, stockQuantity: 22, lowStockThreshold: 4, discountPercent: 10, description: "Slim 1.2kg magnesium alloy ultrabook with 2.8K OLED touch screen.", variants: "RAM: 16GB | Storage: 512GB SSD", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "laptop,ultrabook,oled,forgebook" },
    { id: 119, name: "ForgeRig Desktop Gaming PC", price: 174999, imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=500", category: cElec, brand: "ForgeGaming", rating: 4.9, reviewCount: 42, stockQuantity: 8, lowStockThreshold: 2, discountPercent: 12, description: "Liquid cooled Intel i7 + RTX 4080 16GB gaming tower.", variants: "RAM: 32GB DDR5 | Storage: 2TB NVMe", warranty: "2 Year Warranty", estimatedDeliveryDays: 5, shippingCharges: 499, tags: "computer,pc,desktop,gaming" },
    { id: 120, name: "Curved Gaming Monitor 34\"", price: 34999, imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500", category: cElec, brand: "ForgeVision", rating: 4.7, reviewCount: 89, stockQuantity: 18, lowStockThreshold: 3, discountPercent: 15, description: "Ultrawide 144Hz 1ms WQHD curved HDR gaming monitor.", variants: "Resolution: 3440x1440 | Refresh: 144Hz", warranty: "3 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "monitor,display,gaming,curved" },
    { id: 121, name: "RGB Mechanical Keyboard", price: 3499, imageUrl: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=500", category: cElec, brand: "ForgeKey", rating: 4.6, reviewCount: 230, stockQuantity: 60, lowStockThreshold: 5, discountPercent: 20, description: "Hot-swappable tactile mechanical switches with per-key RGB.", variants: "Switches: Red Linear, Brown Tactile", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "keyboard,mechanical,rgb,gaming" },
    { id: 122, name: "Ergonomic Wireless Gaming Mouse", price: 2999, imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500", category: cElec, brand: "ForgeMouse", rating: 4.8, reviewCount: 310, stockQuantity: 75, lowStockThreshold: 10, discountPercent: 15, description: "26,000 DPI optical sensor with 70h battery and sub-60g shell.", variants: "Color: Matte Black, White", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "mouse,gaming,wireless,ergonomic" },

    { id: 123, name: "Forge Watch Ultra", price: 14999, imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500", category: cElec, brand: "ForgeWatch", rating: 4.9, reviewCount: 148, stockQuantity: 25, lowStockThreshold: 4, discountPercent: 10, description: "Titanium case outdoor smartwatch with dual-frequency GPS & ECG.", variants: "Color: Titanium Gray, Black Strap", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "watch,smartwatch,wearable,ultra" },
    { id: 124, name: "Quantum Fit Band 5", price: 2499, imageUrl: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500", category: cElec, brand: "Quantum", rating: 4.5, reviewCount: 290, stockQuantity: 90, lowStockThreshold: 10, discountPercent: 20, description: "AMOLED fitness tracker with SpO2, continuous heart rate, and 14-day battery.", variants: "Color: Black, Blue, Pink", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "watch,band,fitness,smartwatch" },

    { id: 125, name: "Carbon Fiber Travel Backpack", price: 2999, imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500", category: cApp, brand: "TravelForge", rating: 4.8, reviewCount: 175, stockQuantity: 40, lowStockThreshold: 5, discountPercent: 15, description: "Anti-theft TSA compliant waterproof 30L laptop travel bag.", variants: "Color: Carbon Black, Steel Gray", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "backpack,bag,travel,laptop" },
    { id: 126, name: "MagSafe 3-in-1 Fast Wireless Charger", price: 2499, imageUrl: "https://images.unsplash.com/photo-1622445268465-843846586617?w=500", category: cElec, brand: "ForgePower", rating: 4.7, reviewCount: 132, stockQuantity: 65, lowStockThreshold: 8, discountPercent: 10, description: "15W magnetic charging station for iPhone, Watch & Airpods.", variants: "Color: Matte Black, Pearl White", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "charger,wireless,magsafe,power" },

    { id: 127, name: "Heavyweight Sherpa Zip Hoodie", price: 3999, imageUrl: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=500", category: cApp, brand: "ForgeWear", rating: 4.8, reviewCount: 92, stockQuantity: 30, lowStockThreshold: 4, discountPercent: 15, description: "Ultra-warm sherpa lined winter fleece hoodie.", variants: "Size: S, M, L, XL | Color: Cream, Charcoal", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,hoodie,sherpa,winter" },
    { id: 128, name: "Athletic Performance Pullover Hoodie", price: 2199, imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500", category: cApp, brand: "ForgeWear", rating: 4.6, reviewCount: 114, stockQuantity: 55, lowStockThreshold: 6, discountPercent: 10, description: "Moisture-wicking 4-way stretch gym training hoodie.", variants: "Size: M, L, XL | Color: Stealth Black, Electric Blue", warranty: "6 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "apparel,hoodie,gym,performance" },
    { id: 129, name: "Vintage Washed Crewneck Sweater", price: 2799, imageUrl: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=500", category: cApp, brand: "ForgeWear", rating: 4.7, reviewCount: 78, stockQuantity: 35, lowStockThreshold: 5, discountPercent: 12, description: "Pre-washed retro oversized crewneck fleece sweater.", variants: "Size: S, M, L, XL | Color: Vintage Moss, Dust Rose", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,sweater,crewneck,vintage" },
    { id: 130, name: "Windbreaker Running Jacket", price: 2999, imageUrl: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=500", category: cApp, brand: "ForgeWear", rating: 4.5, reviewCount: 65, stockQuantity: 40, lowStockThreshold: 5, discountPercent: 20, description: "Ultra-lightweight packable rain-proof windbreaker.", variants: "Size: M, L, XL | Color: Cyber Yellow, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,jacket,windbreaker,raincoat" },
    { id: 131, name: "Retro Canvas Court Sneakers", price: 2199, imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500", category: cFoot, brand: "StreetForge", rating: 4.6, reviewCount: 145, stockQuantity: 50, lowStockThreshold: 6, discountPercent: 15, description: "Classic vulcanized rubber sole canvas skate sneakers.", variants: "Size: 7, 8, 9, 10, 11 | Color: Off-White, Black", warranty: "3 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "shoe,sneaker,canvas,skate" },
    { id: 132, name: "All-Terrain Trail Sneakers", price: 5499, imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500", category: cFoot, brand: "TrailForge", rating: 4.9, reviewCount: 88, stockQuantity: 25, lowStockThreshold: 4, discountPercent: 10, description: "Gore-Tex waterproof heavy lug trail running shoes.", variants: "Size: 8, 9, 10, 11 | Color: Olive Drab, Orange Accent", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "shoe,sneaker,trail,outdoor" },
    { id: 133, name: "Suede Penny Loafers", price: 3999, imageUrl: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=500", category: cFoot, brand: "LeatherForge", rating: 4.7, reviewCount: 56, stockQuantity: 28, lowStockThreshold: 4, discountPercent: 15, description: "Italian handcrafted soft suede casual driving loafers.", variants: "Size: 7, 8, 9, 10 | Color: Chocolate Brown, Navy", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "shoe,loafer,suede,formal" },
    { id: 134, name: "Tactical Combat Boots", price: 5999, imageUrl: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=500", category: cFoot, brand: "TacForge", rating: 4.8, reviewCount: 94, stockQuantity: 18, lowStockThreshold: 3, discountPercent: 10, description: "Side-zip military grade tactical assault boots.", variants: "Size: 8, 9, 10, 11 | Color: Coyote Tan, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 4, shippingCharges: 0, tags: "shoe,boot,tactical,combat" },
    { id: 135, name: "Noise Isolating Earbuds Wired", price: 799, imageUrl: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=500", category: cElec, brand: "ForgeAudio", rating: 4.3, reviewCount: 310, stockQuantity: 100, lowStockThreshold: 15, discountPercent: 20, description: "3.5mm gold-plated jack in-ear earphones with mic.", variants: "Color: Black, Silver", warranty: "6 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "headphone,earphone,wired,audio" },
    { id: 136, name: "Desktop Hi-Fi Studio Monitors", price: 11999, imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500", category: cElec, brand: "AcousticForge", rating: 4.9, reviewCount: 45, stockQuantity: 15, lowStockThreshold: 2, discountPercent: 10, description: "Active 50W bookshelf speakers with optical & Bluetooth inputs.", variants: "Color: Walnut Wood, Black", warranty: "2 Year Warranty", estimatedDeliveryDays: 4, shippingCharges: 0, tags: "speaker,audio,studio,hifi" },
    { id: 137, name: "20,000mAh 65W Power Bank", price: 3499, imageUrl: "https://images.unsplash.com/photo-1622445268465-843846586617?w=500", category: cElec, brand: "ForgePower", rating: 4.8, reviewCount: 185, stockQuantity: 60, lowStockThreshold: 6, discountPercent: 15, description: "Laptop-compatible fast charging power bank with digital display.", variants: "Color: Metallic Gray", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "powerbank,charger,battery,usb" },
    { id: 138, name: "Smart LED Desk Lamp", price: 2199, imageUrl: "https://images.unsplash.com/photo-1534349735944-2b3a6f7a268f?w=500", category: cElec, brand: "ForgeHome", rating: 4.6, reviewCount: 92, stockQuantity: 45, lowStockThreshold: 5, discountPercent: 10, description: "Touch-controlled eye-care LED lamp with wireless charging pad.", variants: "Color: Minimal White, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "lamp,light,desk,smart" },
    { id: 139, name: "11-in-1 USB-C Docking Station", price: 4499, imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=500", category: cElec, brand: "ForgeTech", rating: 4.7, reviewCount: 130, stockQuantity: 35, lowStockThreshold: 4, discountPercent: 15, description: "Dual 4K HDMI + 100W PD + Gigabit Ethernet hub.", variants: "Color: Space Gray", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "usb,hub,dock,adapter" },
    { id: 140, name: "4K Ultra HD Streaming Webcam", price: 3999, imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500", category: cElec, brand: "ForgeVision", rating: 4.6, reviewCount: 84, stockQuantity: 40, lowStockThreshold: 5, discountPercent: 20, description: "Autofocus 60FPS webcam with dual noise-cancelling mics.", variants: "Color: Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "webcam,camera,4k,streaming" },
    { id: 141, name: "Wireless Mechanical Numpad", price: 1999, imageUrl: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=500", category: cElec, brand: "ForgeKey", rating: 4.5, reviewCount: 62, stockQuantity: 50, lowStockThreshold: 5, discountPercent: 10, description: "Hot-swappable 21-key mechanical keypad with Bluetooth.", variants: "Color: White/Gray, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "keyboard,numpad,mechanical,wireless" },
    { id: 142, name: "Oversized Leather Gaming Mousepad", price: 1299, imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500", category: cElec, brand: "ForgeMouse", rating: 4.7, reviewCount: 205, stockQuantity: 80, lowStockThreshold: 10, discountPercent: 15, description: "900x400mm waterproof desk mat with stitched edges.", variants: "Color: Midnight Black, Walnut Brown", warranty: "6 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "mousepad,deskmat,gaming,accessory" },
    { id: 143, name: "Aviator Polarized Sunglasses", price: 1799, imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500", category: cApp, brand: "ForgeVision", rating: 4.6, reviewCount: 118, stockQuantity: 50, lowStockThreshold: 5, discountPercent: 20, description: "UV400 protection titanium frame classic aviators.", variants: "Color: Gold/Green, Black/Smoke", warranty: "6 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "sunglasses,shades,aviator,fashion" },
    { id: 144, name: "Minimalist Slim Bifold Leather Wallet", price: 1499, imageUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500", category: cApp, brand: "LeatherForge", rating: 4.8, reviewCount: 160, stockQuantity: 70, lowStockThreshold: 8, discountPercent: 10, description: "RFID blocking genuine Nappa leather pocket wallet.", variants: "Color: Cognac Brown, Stealth Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "wallet,leather,rfid,slim" },
    { id: 145, name: "Thermal Stainless Steel Flask 1000ml", price: 1299, imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500", category: cApp, brand: "ForgeLife", rating: 4.7, reviewCount: 195, stockQuantity: 60, lowStockThreshold: 6, discountPercent: 15, description: "24-hour cold / 12-hour hot double-wall insulated bottle.", variants: "Color: Matte Black, Steel", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "bottle,flask,water,steel" },
    { id: 146, name: "Ergonomic Lumbar Cushion", price: 1899, imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500", category: cApp, brand: "ForgeComfort", rating: 4.6, reviewCount: 88, stockQuantity: 40, lowStockThreshold: 5, discountPercent: 10, description: "Memory foam orthopedic posture support back cushion.", variants: "Color: Charcoal Gray", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "cushion,pillow,lumbar,ergonomic" },
    { id: 147, name: "Noise Cancelling Studio USB Mic", price: 4499, imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500", category: cElec, brand: "ForgeAudio", rating: 4.8, reviewCount: 112, stockQuantity: 30, lowStockThreshold: 4, discountPercent: 15, description: "Cardioid condenser microphone with boom arm for streaming.", variants: "Color: Matte Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "microphone,mic,audio,streaming" },
    { id: 148, name: "Heavy Duty Travel Duffel Bag", price: 2799, imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500", category: cApp, brand: "TravelForge", rating: 4.7, reviewCount: 140, stockQuantity: 35, lowStockThreshold: 5, discountPercent: 20, description: "50L water-resistant sports gym & travel duffel bag.", variants: "Color: Army Olive, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "bag,duffel,travel,gym" },

    // Additional 12 Products for 60+ Total Catalog Items
    { id: 149, name: "Wireless Pro Gaming Controller", price: 3999, imageUrl: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=500", category: cElec, brand: "ForgeGaming", rating: 4.8, reviewCount: 165, stockQuantity: 45, lowStockThreshold: 5, discountPercent: 15, description: "Dual-vibration hall-effect wireless controller for PC & Console.", variants: "Color: Cyber White, Stealth Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "controller,gamepad,gaming,wireless" },
    { id: 150, name: "Ergonomic Vertical Wireless Mouse", price: 2499, imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500", category: cElec, brand: "ForgeMouse", rating: 4.6, reviewCount: 88, stockQuantity: 30, lowStockThreshold: 4, discountPercent: 10, description: "57-degree vertical ergonomic angle to prevent wrist strain.", variants: "Color: Graphite Gray", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "mouse,ergonomic,vertical,wireless" },
    { id: 151, name: "4K Ultra HD Action Camera", price: 8999, imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500", category: cElec, brand: "ForgeVision", rating: 4.7, reviewCount: 94, stockQuantity: 20, lowStockThreshold: 3, discountPercent: 20, description: "Waterproof 30m action cam with dual screen & electronic gyro stabilization.", variants: "Color: Onyx Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "camera,action,4k,waterproof" },
    { id: 152, name: "Smart Home Security Camera 360", price: 2999, imageUrl: "https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=500", category: cElec, brand: "ForgeHome", rating: 4.5, reviewCount: 210, stockQuantity: 50, lowStockThreshold: 6, discountPercent: 15, description: "2K resolution 360-degree pan-tilt indoor security camera with night vision.", variants: "Color: Pure White", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "camera,security,smarthome,wifi" },
    { id: 153, name: "Active Noise Cancelling Headphones Elite", price: 8999, imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500", category: cElec, brand: "ForgeAudio", rating: 4.9, reviewCount: 180, stockQuantity: 25, lowStockThreshold: 4, discountPercent: 15, description: "Flagship 45dB hybrid active noise cancelling over-ear headphones.", variants: "Color: Midnight Navy, Silver", warranty: "2 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "headphone,anc,audio,wireless" },
    { id: 154, name: "Water-Resistant Running Vest", price: 1999, imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500", category: cApp, brand: "ForgeWear", rating: 4.6, reviewCount: 72, stockQuantity: 40, lowStockThreshold: 5, discountPercent: 10, description: "Reflective lightweight running vest with phone pouch and flask pockets.", variants: "Size: S/M, L/XL | Color: High-Vis Yellow, Black", warranty: "6 Months Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "apparel,vest,running,sports" },
    { id: 155, name: "Thermal Base Layer Winter Shirt", price: 1499, imageUrl: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=500", category: cApp, brand: "ForgeWear", rating: 4.7, reviewCount: 110, stockQuantity: 65, lowStockThreshold: 8, discountPercent: 15, description: "Brushed thermal compression top for cold weather activities.", variants: "Size: S, M, L, XL | Color: Charcoal, Black", warranty: "6 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "apparel,shirt,thermal,winter" },
    { id: 156, name: "Classic Aviator Leather Jacket", price: 7999, imageUrl: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=500", category: cApp, brand: "LeatherForge", rating: 4.9, reviewCount: 65, stockQuantity: 15, lowStockThreshold: 2, discountPercent: 10, description: "Handcrafted 100% genuine lambskin aviator leather jacket.", variants: "Size: M, L, XL | Color: Dark Brown, Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 4, shippingCharges: 0, tags: "apparel,jacket,leather,aviator" },
    { id: 157, name: "Pro Speed Fitness Jump Rope", price: 899, imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500", category: cFoot, brand: "ApexForge", rating: 4.5, reviewCount: 195, stockQuantity: 90, lowStockThreshold: 10, discountPercent: 20, description: "360-degree ball bearing aluminum alloy high-speed jump rope.", variants: "Color: Anodized Red, Black", warranty: "6 Months Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "fitness,jumprope,sports,gear" },
    { id: 158, name: "Minimalist Leather Card Holder", price: 999, imageUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500", category: cApp, brand: "LeatherForge", rating: 4.8, reviewCount: 140, stockQuantity: 80, lowStockThreshold: 10, discountPercent: 15, description: "Slim 5-slot genuine top-grain leather card holder with pull strap.", variants: "Color: Vintage Tan, Midnight Black", warranty: "1 Year Warranty", estimatedDeliveryDays: 2, shippingCharges: 0, tags: "wallet,cardholder,leather,accessory" },
    { id: 159, name: "Ultra-Light Carbon Trekking Poles", price: 3499, imageUrl: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=500", category: cFoot, brand: "TrailForge", rating: 4.8, reviewCount: 78, stockQuantity: 30, lowStockThreshold: 4, discountPercent: 10, description: "Pair of 100% carbon fiber collapsible hiking trekking poles.", variants: "Color: Matte Black/Orange", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "hiking,trekking,poles,outdoor" },
    { id: 160, name: "Compact HEPA Desk Air Purifier", price: 3999, imageUrl: "https://images.unsplash.com/photo-1534349735944-2b3a6f7a268f?w=500", category: cElec, brand: "ForgeHome", rating: 4.7, reviewCount: 115, stockQuantity: 35, lowStockThreshold: 4, discountPercent: 15, description: "3-stage true HEPA filtration desktop air purifier with ambient light.", variants: "Color: Polar White", warranty: "1 Year Warranty", estimatedDeliveryDays: 3, shippingCharges: 0, tags: "airpurifier,home,appliance,desktop" }
  ];
};
